# Generated by Django 2.0.1 on 2018-01-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='user_prof_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/profiles/', verbose_name='user_prof_img'),
        ),
    ]
