# Generated by Django 2.0.1 on 2018-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180128_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
